# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 08:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('admin_token', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admins',
            },
        ),
        migrations.CreateModel(
            name='Donater',
            fields=[
                ('donater_firtstName', models.CharField(default=b'FirstName', max_length=50)),
                ('donater_secondName', models.CharField(default=b'SecondName', max_length=50)),
                ('donater_id', models.IntegerField(primary_key=True, serialize=False)),
                ('donater_summOfAllDonations', models.FloatField(default=0)),
                ('donater_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='displaySite.Admin')),
            ],
            options={
                'ordering': ['donater_secondName'],
                'db_table': 'donaters',
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_date', models.DateTimeField()),
                ('donation_text', models.CharField(max_length=100)),
                ('donation_size', models.FloatField()),
                ('donation_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='displaySite.Admin')),
                ('donation_donater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='displaySite.Donater')),
            ],
            options={
                'ordering': ['-donation_date'],
                'db_table': 'donations',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.IntegerField(primary_key=True, serialize=False)),
                ('group_summOfAllDonations', models.FloatField(default=0)),
                ('group_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='displaySite.Admin')),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.AddField(
            model_name='donation',
            name='donation_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='displaySite.Group'),
        ),
    ]
