# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displaySite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donater',
            name='donater_firtstName',
            field=models.CharField(default='FirstName', max_length=50),
        ),
        migrations.AlterField(
            model_name='donater',
            name='donater_secondName',
            field=models.CharField(default='SecondName', max_length=50),
        ),
    ]
