# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displaySite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='admin_firstName',
            field=models.CharField(default=b'FirstName', max_length=50),
        ),
        migrations.AddField(
            model_name='admin',
            name='admin_secondName',
            field=models.CharField(default=b'SecondName', max_length=50),
        ),
    ]
