# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displaySite', '0002_auto_20170513_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donater',
            name='donater_summOfAllDonations',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_size',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_summOfAllDonations',
            field=models.FloatField(default=0),
        ),
    ]
